name: money_library_2021
description: MoneyPlatform Flutter Library
version: 0.0.1


environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  firebase_messaging: ^9.0.0
  cloud_firestore: ^1.0.1
  hive: ^2.0.0

  responsive_builder:
  shared_preferences:
  intl:
  http: ^0.13.0
  uuid:
  flutter_dotenv:
  animations:
  page_transition:
  google_fonts:
  cached_network_image:
  image_picker:
  qrscan:
  circular_profile_avatar:
  autocomplete_textfield:
  qr_flutter:
  dots_indicator:
  file_picker:
  url_launcher:
  introduction_screen:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

