name: money_library_2021
description: MoneyPlatform Flutter Library
version: 0.0.1


environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^1.1.0
  firebase_core: ^1.0.3
  firebase_messaging: ^9.1.1
  cloud_firestore: ^1.0.5
  hive: ^2.0.3

  responsive_builder:
  shared_preferences:
  intl:
  http: ^0.13.1
  uuid:
  flutter_dotenv:
  animations:
  page_transition:
  google_fonts:
  cached_network_image:
  image_picker:
  qrscan:
  circular_profile_avatar:
  autocomplete_textfield:
  qr_flutter:
  dots_indicator:
  file_picker:
  url_launcher:
  introduction_screen:
  oauth2_client: ^2.0.1
  uni_links: ^0.4.0
  syncfusion_flutter_charts: ^19.1.56

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:



